version: '3.0'
services:
  frontend:
    image: "mhart/alpine-node:11"
    volumes:
      - ../pasteblink-frontend:/code
    working_dir: "/code"
    command: "npm run serve"
  # frontend:
  #   image: "gcr.io/pasteblink-222512/pasteblink-frontend:v3"
  # server:
  #   image: "gcr.io/pasteblink-222512/pasteblink:v4"
  #   ports:
  #     - "8888:8888"
  #     - "3000:3000"
  #   environment:
  #     - frontend_server_address=frontend:8080
  #     - cookie_secret=qwweerrt
  server:
    image: "mhart/alpine-node:11"
    volumes:
      - ./:/code
    working_dir: "/code"
    command: "node app"
